//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÖğrenciİşleriOtomasyonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OgrenciIsleriOtomasyonEntities : DbContext
    {
        public OgrenciIsleriOtomasyonEntities()
            : base("name=OgrenciIsleriOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAkademisyen> tblAkademisyen { get; set; }
        public virtual DbSet<tblDersProgramı> tblDersProgramı { get; set; }
        public virtual DbSet<tblDuyuru> tblDuyuru { get; set; }
        public virtual DbSet<tblFakülteBölüm> tblFakülteBölüm { get; set; }
        public virtual DbSet<tblNotlar> tblNotlar { get; set; }
        public virtual DbSet<tblOgrenci> tblOgrenci { get; set; }
        public virtual DbSet<tblProgramSorumlusu> tblProgramSorumlusu { get; set; }
    }
}
