//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÖğrenciİşleriOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDuyuru
    {
        public int ID { get; set; }
        public string DuyuruAdi { get; set; }
        public string Duyuru { get; set; }
        public string DuyuruTarihi { get; set; }
    }
}
